export const data = {
  name: "Yago Ellen",
  role: "Front End Developer",
  about: "Lorem ipsum",
  experience: [
    {
      id: 1,
      coverImg: "/imgs/experience/yobbix.jpg",
      role: "Front End Developer React",
      company: "Yobbix (BeCode project)",
      websiteURL: "",
      dates: "MAR 2025 - APR 2025",
      description: "Develop login page for recruiting company that provides services of recruitment and selection of personnel in Guatemala using AI.",
      softwareStack: [
        "vite",
        "react",
        "tailwind",
        "git",
        "redux",
        "js",
      ],
    },
    {
      id: 2,
      coverImg: "/imgs/experience/lacampana.jpg",
      role: "Full Stack Developer - MERN",
      company: "LACAMPANA (BeCode project)",
      websiteURL: "",
      dates: "DEC 2024 - MAR 2025",
      description: "Develop a e-commerce website for a Colombian company that sells and distributes steel products.",
      softwareStack: [
        "vite",
        "react",
        "tailwind",
        "git",
        "redux",
        "expressjs",
        "mongodb",
        "nodejs",
        "js",
        "daisyui",
        "postman",
      ],
    },
    {
      id: 3,
      coverImg: "/imgs/experience/recambios-cover-img.png",
      role: "Front End Developer React",
      company: "RECAMBIOS (BeCode project)",
      websiteURL: "https://recambios-viaweb-front.onrender.com/home",
      dates: "OCT 2024 - DEC 2024",
      description: "Develop and refactor assigned projects alongside a team of developers and testers.",
      softwareStack: [
        "vite",
        "react",
        "js",
        "material-ui",
        "git",
      ],
    },
    {
      id: 4,
      coverImg: "/imgs/experience/modificars-cover-img.png",
      role: "Web Developer React",
      company: "MODIFI-CARS",
      websiteURL: "https://modifi-cars.com/",
      dates: "AGO 2024 - OCT 2024",
      description: "Design and develop a website for automovile modification, customization and repair workshop.",
      softwareStack: [
        "nextjs",
        "react",
        "ts",
        "tailwind",
        "figma",
        "git",
      ],
    },
    {
      id: 5,
      coverImg: "/imgs/experience/tecsis-cover-img.png",
      role: "Web Developer Wordpress",
      company: "TECSIS INGENIERIA S.A.",
      websiteURL: "https://tecsisingenieria.cl/",
      dates: "JUL 2023 - JUN 2024",
      description: "Design and develop a company website for network services, engineering, construction, and mining.",
      softwareStack: [
        "vite",
        "react",
        "js",
        "bootstrap",
        "figma",
        "git",
        "wordpress",
        "elementor",
      ],
    }
  ],
  projects: [
    {
      id: 1,
      name: "Netflix Home Clone",
      coverImg: "/imgs/projects/netflix-home.png",
      productionURL: "https://the-movies-home.netlify.app/",
      description: "Design and develop a responsive Netflix Home Clone using TheMovieDB API to get data. You can explore all upcoming movies and your prefer genres.",
      softwareStack: [
        "vite",
        "react",
        "js",
        "bootstrap",
        "figma",
        "git",
      ],
    },
    {
      id: 2,
      name: "YagoStore",
      coverImg: "/imgs/projects/yagostore.png",
      productionURL: "https://yagostore.netlify.app/",
      description: "Design and develop a responsive e-commerce demo using FakeStore API. You can enjoy the experience of buy online products like others e-commerce websites and don't worry about money, in YagoStore you can get all products for free.",
      softwareStack: [
        "vite",
        "react",
        "js",
        "bootstrap",
        "figma",
        "git",
      ],
    },
  ]
}